import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="bg-background h-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center">
        <div className="container">
          <h1 className="text-3xl font-bold underline">
            Hello world!
          </h1>
          <div className="grid grid-cols-12 gap-4">
            <div className="col-span-2"></div>
            <div className="bg-grey rounded-lg col-span-6">
              Mensaje de prueba
            </div>
            <div className="col-span-2"></div>

          </div>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
